import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { createTestHarness, parseToolResult } from '@chrischall/mcp-utils/test';
import { OFWClient } from '../src/client.js';
import { registerHealthcheckTools } from '../src/tools/healthcheck.js';

/**
 * A CloudFront WAF block is not a credential problem (chrischall/mcp-host#1015).
 *
 * The password sign-in turned any non-2xx from `POST /ofw/login` into
 * `OFW login failed: 403 Forbidden` and dropped the page, so a blocked
 * sign-in reached `ofw_healthcheck` with nothing to say what refused it — and
 * was reported as `no_credential`, "No OFW credential is configured", to a
 * user whose OFW_USERNAME/OFW_PASSWORD were set.
 *
 * These run the REAL client and the REAL auth resolver against the page
 * CloudFront serves, so they fail if anything between the response and the
 * healthcheck drops what the shared classifier reads.
 */

// CloudFront's block page, as served (whitespace trimmed, ids made up).
const CLOUDFRONT_BLOCK =
  '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">' +
  '<HTML><HEAD><META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">' +
  '<TITLE>ERROR: The request could not be satisfied</TITLE></HEAD><BODY>' +
  '<H1>403 ERROR</H1><H2>The request could not be satisfied.</H2><HR noshade size="1px">' +
  'Request blocked. We can\'t connect to the server for this app or website at this time. ' +
  'There might be too much traffic or a configuration error. Try again later, or contact the app or ' +
  'website owner.<BR clear="all">If you provide content to customers through CloudFront, you can find ' +
  'steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.' +
  '<BR clear="all"><HR noshade size="1px"><PRE>Generated by cloudfront (CloudFront)\n' +
  'Request ID: AbCdEfGhIjKlMnOpQrStUvWxYz0123456789abcdefghijklmnopqr==</PRE><ADDRESS></ADDRESS></BODY></HTML>';

function blocked(): Response {
  return new Response(CLOUDFRONT_BLOCK, {
    status: 403,
    statusText: 'Forbidden',
    headers: { 'content-type': 'text/html', 'x-cache': 'Error from cloudfront', server: 'CloudFront' },
  });
}

function json(status: number, body: unknown): Response {
  return new Response(JSON.stringify(body), { status, headers: { 'content-type': 'application/json' } });
}

/** OFW's two-step form login, answered successfully, then `api` for everything else. */
function ofw(api: () => Response) {
  return async (input: string | URL | Request): Promise<Response> => {
    const url = String(input instanceof Request ? input.url : input);
    if (url.endsWith('/ofw/login.form')) {
      return new Response(null, { status: 303, headers: { 'set-cookie': 'SESSION=abc; Path=/ofw' } });
    }
    if (url.endsWith('/ofw/login')) return json(200, { auth: 'bearer-xyz', redirectUrl: '/app/home' });
    return api();
  };
}

interface Result {
  ok: boolean;
  credential: { source: string | null; resolved: boolean };
  error?: { kind: string; message: string; detail?: Record<string, unknown> };
  hint: string;
}

async function healthcheck(client: OFWClient): Promise<Result> {
  const h = await createTestHarness((server) => registerHealthcheckTools(server, client));
  const res = await h.client.callTool({ name: 'ofw_healthcheck', arguments: {} });
  await h.close?.();
  return parseToolResult<Result>(res as never);
}

describe('a CloudFront block reads as edge_blocked, not a credential problem', () => {
  let fetchMock: ReturnType<typeof vi.fn>;

  beforeEach(() => {
    fetchMock = vi.fn();
    vi.stubGlobal('fetch', fetchMock);
    process.env.OFW_USERNAME = 'parent@example.com';
    process.env.OFW_PASSWORD = 'pw';
    process.env.OFW_DISABLE_FETCHPROXY = '1';
  });

  afterEach(() => {
    vi.unstubAllGlobals();
    vi.restoreAllMocks();
    delete process.env.OFW_USERNAME;
    delete process.env.OFW_PASSWORD;
    delete process.env.OFW_DISABLE_FETCHPROXY;
  });

  it('on the password sign-in', async () => {
    fetchMock.mockImplementation(async () => blocked());

    const r = await healthcheck(new OFWClient());

    expect(r.ok).toBe(false);
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail?.vendor).toBe('CloudFront');
    // Not the "nothing is configured" copy for a configured account.
    expect(r.hint).not.toMatch(/No OFW credential is configured/);
    expect(r.hint).toMatch(/CDN\/WAF/);
  });

  it('on the probe itself, after a good sign-in', async () => {
    fetchMock.mockImplementation(ofw(blocked));

    const r = await healthcheck(new OFWClient());

    expect(r.ok).toBe(false);
    expect(r.credential.source).toBe('env');
    expect(r.error?.kind).toBe('edge_blocked');
    expect(r.error?.detail?.vendor).toBe('CloudFront');
  });

  it('a blocked sign-in does not latch the password as rejected', async () => {
    fetchMock.mockImplementation(async () => blocked());
    const client = new OFWClient();
    expect((await healthcheck(client)).error?.kind).toBe('edge_blocked');

    // The block lifted: the same credentials are sent again rather than
    // refused by the rejection latch until a restart.
    fetchMock.mockImplementation(ofw(() => json(200, [{ id: 1 }])));
    expect((await healthcheck(client)).ok).toBe(true);
  });

  it("control: the API's own JSON 403 on the probe is not called an edge block", async () => {
    fetchMock.mockImplementation(ofw(() => json(403, { message: 'Access is denied' })));

    const r = await healthcheck(new OFWClient());

    expect(r.ok).toBe(false);
    expect(r.error?.kind).not.toBe('edge_blocked');
  });
});
